[package]
name = "pubsub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.132"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = [ "full" ]}
chrono = "0.4.19"
